KortKiralamaOdevi/KortKiralamaOdevi/Areas/admin/Controllers/KortlarController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using KortKiralamaOdevi.Models;
using KortKiralamaOdevi.Models.dbEntities;

namespace KortKiralamaOdevi.Areas.admin.Controllers
{
    [Authorize(Roles="Admin")]
    public class KortlarController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: admin/Kortlar
        public ActionResult Index()
        {
            return View(db.Kortlar.ToList());
        }

        // GET: admin/Kortlar/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Kort kort = db.Kortlar.Find(id);
            if (kort == null)
            {
                return HttpNotFound();
            }
            return View(kort);
        }

        // GET: admin/Kortlar/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: admin/Kortlar/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,KortAdi,ResimUrl")] Kort kort)
        {
            if (ModelState.IsValid)
            {
                db.Kortlar.Add(kort);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(kort);
        }

        // GET: admin/Kortlar/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Kort kort = db.Kortlar.Find(id);
            if (kort == null)
            {
                return HttpNotFound();
            }
            return View(kort);
        }

        // POST: admin/Kortlar/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,KortAdi,ResimUrl")] Kort kort)
        {
            if (ModelState.IsValid)
            {
                db.Entry(kort).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(kort);
        }

        // GET: admin/Kortlar/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Kort kort = db.Kortlar.Find(id);
            if (kort == null)
            {
                return HttpNotFound();
            }
            return View(kort);
        }

        // POST: admin/Kortlar/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Kort kort = db.Kortlar.Find(id);
            db.Kortlar.Remove(kort);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

KortKiralamaOdevi/KortKiralamaOdevi/Controllers/RezervasyonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using KortKiralamaOdevi.Areas.admin.Models;
using KortKiralamaOdevi.Controllers;
using KortKiralamaOdevi.Models;
using KortKiralamaOdevi.Models.dbEntities;
using Microsoft.AspNet.Identity.Owin;

namespace KortKiralamaOdevi.Controllers
{
    public class RezervasyonController : BaseController
    {
        RezervasyonBusiness rezervasyonBusiness = new RezervasyonBusiness();
        public ActionResult Index(int kortId)
        {
            ViewBag.NormalSayfa = true;
            if (GetLoginedUser() != null && User.IsInRole("Admin"))
                ViewBag.NormalSayfa = false;
            

            var liste = rezervasyonBusiness.GetirRezervasyonBilgileriIndexViewModel(kortId);
            return View(liste);
        }

        public ActionResult _RezervasyonDetay(int rezervasyonId)
        {
            ViewBag.NormalSayfa = true;
            if (GetLoginedUser() != null && User.IsInRole("Admin"))
                ViewBag.NormalSayfa = false;
            var liste = rezervasyonBusiness.GetirRezevasyonDetayBilgileri(rezervasyonId);
            return View(liste);
        }

        public ActionResult RezervasyonYap()
        {
            using (ApplicationDbContext db =new ApplicationDbContext())
            {
                var kortlar = db.Kortlar.Select(x => new
                {
                    x.ID,
                    x.KortAdi
                }).ToList();
                ViewBag.Kortlar = new SelectList(kortlar, "ID", "KortAdi",kortlar.FirstOrDefault().ID);
            }
            return View();
        }
        [HttpPost]
        public ActionResult RezervasyonYap(RezervasyonYapViewModel model)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.Hata = "";
                using (ApplicationDbContext db = new ApplicationDbContext())
                {
                    var kortlar = db.Kortlar.Select(x => new
                    {
                        x.ID,
                        x.KortAdi
                    }).ToList();
                    ViewBag.Kortlar = new SelectList(kortlar, "ID", "KortAdi", model.FKKortID);
                }
                return View(model);
            }
            if (GetLoginedUser()==null &&(string.IsNullOrEmpty(model.Ad)||string.IsNullOrEmpty(model.Soyad)||string.IsNullOrEmpty(model.TelNo)))
            {
                ViewBag.Hata = "Ad soyad telefon no dolu olmalıdır";
                using (ApplicationDbContext db = new ApplicationDbContext())
                {
                    var kortlar = db.Kortlar.Select(x => new
                    {
                        x.ID,
                        x.KortAdi
                    }).ToList();
                    ViewBag.Kortlar = new SelectList(kortlar, "ID", "KortAdi", model.FKKortID);
                }
                return View(model);
            }
            using (ApplicationDbContext db = new ApplicationDbContext())
            {
                double ucret;
                var gucret = db.KortGunlukUcretler.FirstOrDefault(x => x.FKKortID == model.FKKortID &&
                                                                       x.Gun == model.BaslangicTarihi.DayOfWeek);
                if (gucret == null)
                    ucret = GetirDefaultKortUcreti();
                else
                    ucret = gucret.Ucret;

                ucret = ucret * model.Seans;
                Odeme odeme = new Odeme()
                {
                    OdenecekTutar = ucret,
                    OdendiMi = !model.oyunSonrasiOdenecek
                };

                Rezervasyon rez = new Rezervasyon();

                var kullanici = GetLoginedUser();
                if (kullanici != null)
                {
                    rez.FKUyeID = kullanici.Id;
                    model.Ad = kullanici.Ad;
                    model.Soyad = kullanici.Soyad;
                    model.TelNo = kullanici.TelNo;
                }
                else
                {
                    rez.Ad = model.Ad;
                    rez.Soyad = model.Soyad;
                    rez.TelNo = model.TelNo;
                }

                rez.BaslangicTarihi = model.BaslangicTarihi.AddHours(model.BaslangicSaati);
                rez.BitisTarihi = rez.BaslangicTarihi.AddHours(model.Seans);
                rez.FKKortID = model.FKKortID;

                var baslangicTarihi = model.BaslangicTarihi.AddHours(model.BaslangicSaati);
                if (db.Rezervasyonlar.Any(x=>x.BaslangicTarihi== baslangicTarihi))
                {
                    odeme.OdendiMi = false;
                    model.oyunSonrasiOdenecek = true;
                    rez.EnumRezervasyonDurumu = EnumRezervasyonDurumu.Beklemede;
                    model.Bilgi = "Rezervasyon yapmak istediğiniz gün ve saatte daha önceden alınan rezervasyon olduğu için rezervasyonunuzu beklemeye aldık";
                }


                db.Odeme.Add(odeme);
                db.SaveChanges();

                rez.FKOdemeID = odeme.ID;
                
                db.Rezervasyonlar.Add(rez);
                db.SaveChanges();

                var kort = db.Kortlar.Find(rez.FKKortID);
                model.KortAdi = kort.KortAdi;
                model.Bilgi = string.IsNullOrEmpty(model.Bilgi) ? "Rezervasyonunuz Oluşturuldu" : model.Bilgi;



            }
            return View("RezervasyonSonuc",model);
        }

        public ActionResult OdemeSecimi(int kortid, int seans, DateTime baslangicTarihi)
        {
            using (ApplicationDbContext db = new ApplicationDbContext())
            {
                double ucret;
                var gucret = db.KortGunlukUcretler.FirstOrDefault(x => x.FKKortID == kortid && x.Gun ==baslangicTarihi.DayOfWeek);
                if (gucret == null)
                    ucret = GetirDefaultKortUcreti();
                else
                    ucret = gucret.Ucret;

                return View(ucret*seans);
                
            }
        }
    }
}

KortKiralamaOdevi/KortKiralamaOdevi/Controllers/TestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using KortKiralamaOdevi.Models;
using KortKiralamaOdevi.Models.dbEntities;

namespace KortKiralamaOdevi.Controllers
{
    
    public class TestController : BaseController
    {
        public ActionResult Index()
        {
            using (ApplicationDbContext db = new ApplicationDbContext())
            {
                var item = db.Users.FirstOrDefault();
                var listelenecekler = db.Kortlar.Select(x => new
                {
                    x.ID,
                    x.KortAdi,
                    x.ResimUrl,
                    Ucret = x.GunlukKortUcretleri.First(gunlukUcret => gunlukUcret.Gun == DateTime.Now.DayOfWeek).Ucret
                });
                return View(item);
            }
        }
        [Authorize]
        public ActionResult LoginOlmadanGireme()
        {
            return Json("");
        }
        [Authorize(Roles = "Admin")]
        public ActionResult AdminOlmadanGireme()
        {
            var girisYapanKullanici = GetLoginedUser();
            return Json(girisYapanKullanici,JsonRequestBehavior.AllowGet);
        }
        [Authorize(Roles = "Admin")]
        public ActionResult RezervasyonVerisiDoldur()
        {
            using (ApplicationDbContext context=new ApplicationDbContext())
            {
                Random rnd = new Random();
                var tumRezervasyonlar = context.Rezervasyonlar.ToList();
                foreach (var rezervasyon in tumRezervasyonlar)
                    context.Rezervasyonlar.Remove(rezervasyon);


                context.SaveChanges();
                var userId = context.Users.FirstOrDefault().Id;
                var kortId = context.Kortlar.FirstOrDefault().ID;
                for (int i = 0; i < 7; i++)
                {
                    Odeme odeme = new Odeme();
                    odeme.OdenecekTutar = rnd.Next(0, 12);
                    odeme.OdendiMi = rnd.Next(0, 999) % 2 == 1;
                    context.Odeme.Add(odeme);
                    context.SaveChanges();


                    Rezervasyon rez = new Rezervasyon();
                    DateTime baslangic = DateTime.Now.AddDays(i);

                    TimeSpan ts = new TimeSpan(rnd.Next(9, 16), rnd.Next(0, 999) % 2 == 1 ? 30 : 0, 0);
                    baslangic = baslangic.Date + ts;
                    rez.BaslangicTarihi = baslangic;
                    rez.BitisTarihi = rez.BaslangicTarihi.AddHours(1);

                    rez.FKUyeID = userId;
                    rez.FKOdemeID = odeme.ID;
                    rez.EnumRezervasyonDurumu = EnumRezervasyonDurumu.Aktif;
                    rez.FKKortID = kortId;
                    context.Rezervasyonlar.Add(rez);
                    context.SaveChanges();

                }

                return RedirectToAction("Index", "Dashboard", new {Area = "admin"});

            }
        }
    }
}

KortKiralamaOdevi/KortKiralamaOdevi/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Admin Paneli</title>
    @Styles.Render("~/bundles/admincss")
    @RenderSection("Styles",false)
</head>
<body class="fixed-nav sticky-footer bg-dark" id="page-top">
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
        <a class="navbar-brand" href="/">Anasayfa</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav navbar-sidenav" id="exampleAccordion">
              @Html.Partial("_AdminMenu")
            </ul>
          
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("LogOff","Account",new {Area=""})">
                        <i class="fa fa-fw fa-sign-out"></i>Çıkış Yap
                    </a>
                </li>
            </ul>
        </div>
    </nav>
    <div class="content-wrapper">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12" style="padding: 25px">
                    @RenderBody()
                </div>
            </div>
        </div>
        <!-- /.container-fluid-->
        <!-- /.content-wrapper-->
        <footer class="sticky-footer">
            <div class="container">
                <div class="text-center">
                    <small>Kort Kiralama Sistemi</small>
                </div>
            </div>
        </footer>
        <!-- Scroll to Top Button-->
        <a class="scroll-to-top rounded" href="#page-top">
            <i class="fa fa-angle-up"></i>
        </a>
        <!-- Logout Modal-->
        <!-- Bootstrap core JavaScript-->
        @Scripts.Render("~/bundles/adminJs")
        <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
        @RenderSection("Scripts", false)
    </div>
</body>
</html>

KortKiralamaOdevi/KortKiralamaOdevi/Views/Shared/_AdminMenu.cshtml
<li class="nav-item" data-toggle="tooltip" data-placement="right" title="Components">
    <a class="nav-link" href="@Url.Action("Index","Dashboard",new {Area="admin"})">

        <span class="nav-link-text">Admin Anasayfa</span>
    </a>
</li>


<li class="nav-item" data-toggle="tooltip" data-placement="right" title="Components">
    <a class="nav-link nav-link-collapse collapsed" data-toggle="collapse" href="#ckort">
        <span class="nav-link-text">Kort İşlemleri</span>
    </a>
    <ul class="sidenav-second-level collapse" id="ckort">
        <li>
            <a href="@Url.Action("Index","Kortlar",new {Area="admin"})">Kortları Listele</a>
        </li>
        <li>
            <a href="@Url.Action("Create","Kortlar",new {Area="admin"})">Kort Ekle</a>
        </li>
    </ul>
</li>
<li class="nav-item" data-toggle="tooltip" data-placement="right" title="Components">
    <a class="nav-link nav-link-collapse collapsed" data-toggle="collapse" href="#ckortucret">
        <span class="nav-link-text">Kort Günlük Ücret İşlemleri</span>
    </a>
    <ul class="sidenav-second-level collapse" id="ckortucret">
        <li>
            <a href="@Url.Action("Index","KortGunlukUcretleri",new {Area="admin"})">Kortları Listele</a>
        </li>
        <li>
            <a href="@Url.Action("Create","KortGunlukUcretleri",new {Area="admin"})">Kort Ekle</a>
        </li>
    </ul>
</li>


<li class="nav-item" data-toggle="tooltip" data-placement="right" title="Components">
    <a class="nav-link nav-link-collapse collapsed" data-toggle="collapse" href="#ckull">
        <span class="nav-link-text">Kullanıcı İşlemleri</span>
    </a>
    <ul class="sidenav-second-level collapse" id="ckull">
        <li>
            <a href="@Url.Action("Users","Account",new {Area=""})">Kullanıcıları Listele</a>
        </li>
        <li>
            <a href="@Url.Action("Register","Account",new {Area=""})">Kullanıcı Ekle</a>
        </li>
    </ul>
</li>



<li class="nav-item" data-toggle="tooltip" data-placement="right" title="Components">
    <a class="nav-link" href="@Url.Action("RezervasyonVerisiDoldur","Test",new {Area=""})">

        <span class="nav-link-text">Rezervasyon Seed</span>
    </a>
</li>

KortKiralamaOdevi/KortKiralamaOdevi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="author" content="Colorlib">
    <meta name="description" content="#">
    <meta name="keywords" content="#">
    <!-- Favicons -->
    <link rel="shortcut icon" href="#">
    <!-- Page Title -->
    <title>Listing &amp; Directory Website Template</title>
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,400i,500,700,900" rel="stylesheet">
    <!-- Simple line Icon -->
    @Styles.Render("~/bundles/maincss")
    @RenderSection("Styles", false)
    <style>
        #bodyDiv {
            min-height: 1200px;
        }
    </style>
</head>
<body>
    <!--============================= HEADER =============================-->
    <div class="dark-bg sticky-top">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <nav class="navbar navbar-expand-lg navbar-light">
                        <a class="navbar-brand" href="/">Anasayfa</a>
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="icon-menu"></span>
                        </button>
                        <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
                            <ul class="navbar-nav">


                                <li class="nav-item active">
                                    <a class="nav-link" href="@Url.Action("RezervasyonYap","Rezervasyon",new {Area=""})">Rezervasyon Yap</a>
                                </li>

                                <li>
                                    @if (StaticDegiskenler.KullaniciGirisYaptiMi)
                                    {
                                        <a class="nav-link" href="@Url.Action("LogOff","Account",new {Area=""})">
                                            <i class="fa fa-fw fa-sign-out"></i>Çıkış Yap
                                        </a>
                                    }
                                    else
                                    {
                                        <a href="@Url.Action("Login", "Account", new {Area = ""})" class="btn btn-outline-light top-btn"> Giriş Yap</a>

                                    }
                                </li>
                            </ul>
                        </div>
                    </nav>
                </div>
            </div>
        </div>
    </div>
    <div id="bodyDiv">
        @RenderBody()
        <div class="clearfix"></div>
    </div>
    <footer class="main-block dark-bg" style="padding: 10px 0">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="copyright">
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        <p>Kort Kiralama Sistemi</p>
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->

                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!--//END FOOTER -->
    @Scripts.Render("~/bundles/mainJs")
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    @RenderSection("Scripts", false)
    <script>
        var swiper = new Swiper('.swiper-container', {
            slidesPerView: 3,
            slidesPerGroup: 3,
            loop: true,
            loopFillGroupWithBlank: true,
            pagination: {
                el: '.swiper-pagination',
                clickable: true,
            },
            navigation: {
                nextEl: '.swiper-button-next',
                prevEl: '.swiper-button-prev',
            },
        });</script>
    <script>
        if ($('.image-link').length) {
            $('.image-link').magnificPopup({
                type: 'image',
                gallery: {
                    enabled: true
                }
            });
        }
        if ($('.image-link2').length) {
            $('.image-link2').magnificPopup({
                type: 'image',
                gallery: {
                    enabled: true
                }
            });
        }</script>
</body>
</html>